[package]
name = "tja"
version = "0.1.0"
edition = "2024"

[lib]
name = "tja"
path = "src/lib.rs"

[dependencies]
derive_more = { version = "2.0.1", features = ["from", "display"] }
iris = { version = "0.1.0", path = "../iris" }
typed-generational-arena = "0.2"
index_vec = "0.1.4"
paste = "1.0.15"
