[package]
name = "iris"
version = "0.1.0"
edition = "2024"

[lib]
name = "iris"
path = "src/lib.rs"

[build-dependencies]
lalrpop = "0.22.2"

[dependencies]
lalrpop-util = { version = "0.22.2", features = ["lexer", "unicode"] }
